GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/6608432cb7fb7f3c147c4ba5
###
GET http://localhost:3001/api/persons/6608432cb7fb7f3c147c4ba6

###
DELETE http://localhost:3001/api/persons/5

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "as",
    "number": "123456789"
}

###

GET http://localhost:3001/info

###
PUT http://localhost:3001/api/persons/660862c7c089da02dc4037a4 HTTP/1.1
content-type: application/json

{
    "name": "salman",
    "number": "1234"
}